Implement new CI on Github Actions
keystone-enclave/keystone pull request #399
Opened 2023-12-21 21:59 UTC by grg-haas

This PR creates a new efficient CI system for the Buildroot-based build system introduced a while ago. It includes full build tests for each supported platform (currently `generic` and `unmatched`, with `cva6` and `mpfs` landing soon) as well as full-stack runtime tests for the 32 and 64-bit generic platforms. CI times are kept low by heavily relying on Github Actions caching, where we save the latest compiler cache and Buildroot package cache at the end of each run. On average, the `generic` platforms build in 10 minutes while the `unmatched` platform builds in 13 (with a hot cache). With a cold cache, the builds take about an hour but will then refresh the caches so that future ones take much less time.

2023-12-21 22:00 UTC, grg-haas commented
@evgenyp67 I've added you as a reviewer since some of my changes involve the new loader component. Please let me know if you see any issues, but with these changes the 32-bit configurations should also be fully supported now.

2023-12-29 19:39 UTC, evgenyp67 requested changes
The changes look great, very happy that we will soon have CI back on!

The only issue I saw is in `test-system.yml` I noticed that `tests.ke` is ran but `attestor.ke` is not. The latter tests that the attestation report is equal to the expected one, while `tests.ke` only checks that the report is successfully generated. I believe we should do both.

2023-12-29 21:37 UTC, grg-haas commented
Thanks @evgenyp67 ! I've added the attestation test as well. @dayeol , any thoughts?

2023-12-29 21:51 UTC, evgenyp67 approved these changes

2024-01-06 19:28 UTC, merged